name: Build Aseprite with Skia (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Aseprite from Source
    runs-on: windows-latest

    steps:
    - name: Checkout Aseprite Source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Required Directories
      run: |
        mkdir C:\deps
        mkdir C:\aseprite\build

    - name: Download and Extract Depot Tools
      run: |
        curl -L -o depot_tools.zip https://storage.googleapis.com/chrome-infra/depot_tools.zip
        tar -xf depot_tools.zip -C C:\deps
        echo "C:\deps\depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Clone Skia
      run: |
        cd C:\deps
        git clone https://github.com/google/skia.git
        cd skia
        python tools\git-sync-deps
      shell: cmd

    - name: Build Skia
      run: |
        cd C:\deps\skia
        bin\gn gen out\Release-x86 --args="is_official_build=true is_component_build=false is_debug=false skia_use_dng_sdk=false skia_use_libheif=false skia_use_libjpeg_turbo_encode=true skia_use_libjpeg_turbo_decode=true skia_use_libpng=true skia_use_libwebp=false skia_use_expat=true skia_use_zlib=true skia_enable_skottie=false target_cpu=\"x86\""
        ninja -C out\Release-x86
      shell: cmd

    - name: Configure Aseprite with Skia
      run: |
        cd C:\aseprite\build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DLAF_BACKEND=skia `
              -DSKIA_DIR=C:\deps\skia `
              -DSKIA_LIBRARY_DIR=C:\deps\skia\out\Release-x86 `
              -DSKIA_LIBRARY=skia.lib `
              -G Ninja ..
      shell: powershell

    - name: Build Aseprite
      run: |
        cd C:\aseprite\build
        ninja aseprite
      shell: cmd

    - name: Upload Full bin/ Folder
      uses: actions/upload-artifact@v3
      with:
        name: aseprite-bin
        path: C:\aseprite\build\bin\
