name: Build and Upload Aseprite (Windows, Skia)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-giflib
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-zlib

      - name: Download Skia precompiled
        run: |
          curl -L -o Skia-Windows-Release-x64.zip https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
          mkdir skia
          unzip -q Skia-Windows-Release-x64.zip -d skia

      - name: Build Aseprite with Skia
        shell: msys2 {0}
        run: |
          SKIA_DIR="$(cygpath -m "${GITHUB_WORKSPACE}/skia")"
          SKIA_LIBRARY_DIR="$SKIA_DIR/out/Release-x64"
          SKIA_LIBRARY="$SKIA_LIBRARY_DIR/skia.lib"
          mkdir build
          cd build
          cmake -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR="$SKIA_DIR" \
            -DSKIA_LIBRARY_DIR="$SKIA_LIBRARY_DIR" \
            -DSKIA_LIBRARY="$SKIA_LIBRARY" \
            -DCMAKE_INSTALL_PREFIX=$(cygpath -m "${GITHUB_WORKSPACE}/install") ..
          ninja
          ninja install

      - name: Archive build output
        run: |
          Compress-Archive -Path install\* -DestinationPath aseprite-windows-skia.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows-skia
          path: aseprite-windows-skia.zip
