name: Build and Upload Aseprite (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-libjpeg-turbo
            mingw-w64-x86_64-giflib
            mingw-w64-x86_64-libwebp
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-fontconfig
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-zlib

      - name: Build Aseprite
        shell: msys2 {0}
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DCMAKE_INSTALL_PREFIX=../install ..
          ninja
          ninja install

      - name: Archive build output
        run: |
          Compress-Archive -Path install\* -DestinationPath aseprite-windows.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows
          path: aseprite-windows.zip
